### ISSUE TITLE
Only cover packages that the tested package depends on

### ISSUE THREAD

**Issue by nkovacs** [ory/go-acc#1]
I get a lot of "warning: no packages being tested depend on *packagename*" errors because each package is tested with every other package, even if it doesn't import it. This also skews coverage, because I have a few generated packages that I don't want counted.

It would be better to only cover the packages that the tested package actually depends on. Something like this: https://github.com/ory/go-acc/compare/master...nkovacs:master

**Comment by arekkas** [comment]
> I have a few generated packages that I don't want counted.

Couldn't something like `go-acc $(go list | grep -v ignore-this-dir` solve this as well?

> I get a lot of "warning: no packages being tested depend on packagename" errors because each package is tested with every other package, even if it doesn't import it. 

We could grep for this error and silently reject it. It is annoying me as well sometimes.

> This also skews coverage

That depends, imagine you have a `cmd` package for command line tooling which imports other packages that contain logic. The cmd package may not have any tests and thus be wrongfully discarded by the coverage report.

**Comment by nkovacs** [comment]
Yeah, you're right. `.Deps` also doesn't include packages imported from tests only, and I do want to cover those.
