### ISSUE TITLE
go get github.com/ory/go-acc fails  - cannot find package 

### ISSUE THREAD

**Issue by dharnitski** [ory/go-acc#15]
fails with message

`package go.opentelemetry.io/otel/plugin/httptrace: cannot find package "go.opentelemetry.io/otel/plugin/httptrace"`

Reproduced for GO 1.14.3 on Mac and Linux

**Comment by aeneasr** [comment]
Fails for me only when `GO111MODULES=off`, for you?

**Comment by dharnitski** [comment]
> Fails for me only when `GO111MODULES=off`, for you?

Same for me. We still use `dep` in our production project.

This is reproducible sample:
https://circleci.com/gh/dharnitski/go-coverage-sample/8
https://github.com/dharnitski/go-coverage-sample/tree/go-acc

**Comment by aeneasr** [comment]
Ok, we can probably strip ory/x from here
