### ISSUE TITLE
../../ory/go-acc/cmd/root.go:182:2: missing return at end of function

### ISSUE THREAD

**Issue by dharnitski** [ory/go-acc#18]
go get -u github.com/ory/go-acc
go-acc ./...

# github.com/ory/go-acc/cmd
../../ory/go-acc/cmd/root.go:182:2: missing return at end of function

**Comment by aeneasr** [comment]
🤦

**Comment by dharnitski** [comment]
Thank for quick response. I appreciate your help!

**Comment by aeneasr** [comment]
I hope it resolves your issues :)

**Comment by dharnitski** [comment]
It works now!

**Comment by aeneasr** [comment]
Nice :)
