### ISSUE TITLE
go-acc ./... fails with message `exec: already started`

### ISSUE THREAD

**Issue by dharnitski** [ory/go-acc#21]
exec: already started
Exited with code exit status 1

Issue stared about 30 min ago

Likely related to this commit:
https://github.com/ory/go-acc/commit/e95c7e380a398cc489841d633fa2a2fa5cb4a3df

reproducible sample - https://circleci.com/gh/dharnitski/go-coverage-sample/9

Line 155 should be removed. It is duplicate
![image](https://user-images.githubusercontent.com/1175110/85435538-954e3680-b555-11ea-98df-bd5373ff1d08.png)

**Comment by aeneasr** [comment]
😅 Gonna fix this

**Comment by aeneasr** [comment]
You can probably work around it by checking out the version prior!

**Comment by dharnitski** [comment]
I am in GOPATH and getting 
go: cannot use path@version syntax in GOPATH mode

when try to execute 

`go get -u github.com/ory/go-acc@v0.2.3`
