### ISSUE TITLE
Modifies `go test -json` output, making it invalid JSON

### ISSUE THREAD

**Issue by dlipovetsky** [ory/go-acc#29]
The output of `go test -json` contains coverage summaries, e.g.,
```
{"Time":"2021-06-04T15:08:38.3398169-07:00","Action":"output","Package":"example","Output":"coverage: 14.8% of statements\n"}
```

These lines are modified by https://github.com/ory/go-acc/blob/65df6aba56a7fcadbe5fa68a2b2529171778b0ab/cmd/root.go#L187

Namely, the last part of the split is removed: 
```
{"Time":"2021-06-04T15:08:38.3398169-07:00","Action":"output","Package":"example","Output":"coverage: 14.8
```
Unfortunately, that is no longer parsable JSON.

**Comment by aeneasr** [comment]
Would you be up for a PR? :)

**Comment by dlipovetsky** [comment]
Thanks for triaging this!

The line was introduced to "improve pipeline handling" in https://github.com/ory/go-acc/commit/ddc355013f90fea78d83d3a6c71f1d37ac07ecd5. I'm honestly not sure what the right fix would be. I don't want to regress pipe handling. Any suggestions? With some direction, I should be able to PR it.

**Comment by aeneasr** [comment]
One possibility would be to check if the string is JSON and leave it untouched if it isn't json

**Comment by aeneasr** [comment]
I resolved this issue on master!
