### ISSUE TITLE
there is something wrong when i run go get github.com/ory/go-acc 

### ISSUE THREAD

**Issue by ucmnmn** [ory/go-acc#3]
hi guys ,you do great job,
but when i run  go get github.com/ory/go-acc,  it show me the code like below:

package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

 and when i try the url in the error code, i find the transform is move to https://godoc.org/golang.org/x/text/transform

i am new in go lang, wish you guys can fix it

**Comment by aeneasr** [comment]
Hey, this is a go-related problem with (your) network connectivity or the server at `216.239.37.1`. Nothing we can do. Just try it again in a couple of minutes or in an hour or so.

**Comment by ucmnmn** [comment]
ok,i got it thks
