### ISSUE TITLE
How to ignore particular file(s)?

### ISSUE THREAD

**Issue by user3301** [ory/go-acc#30]
The `--ignore` seems only accepts packages to be ignored. How do I tell go-acc to ignore a single go file?

**Comment by aeneasr** [comment]
Please check how that is possible with `go test`. If it is not possible with `go test` it is not possible with go-acc either!

**Comment by naeem-shaikh-tw** [comment]
@aeneasr how does it ignore the packages with `--ignore` flag? is it possible with go test?
